### PR TITLE
Truncate very long appointment summary to shrink indicator menu

### LINKED ISSUE #29: Very wide indicator menu
Prerequisites:

1. Installed Ubuntu MATE 20.10 (Groovy Gorilla).
2. Preconfigured calendar in GNOME Evolution.
3. `dconf reset /org/ayatana/indicator/datetime/show-events` (Apply default value true for the key).

Steps to reproduce:

1. Create or import an appointment with quite long summary.
2. Click to datetime indicator and open context menu.

Expected behavior:

1. Width of the menu is the same as without the appointment.

Current behavior:

1. The menu is stretching.

<details>
  <summary>Some screenshots from different years.</summary>

February 2020
May 2021

</details>

Related bug on Launchpad https://bugs.launchpad.net/ubuntu/+source/indicator-datetime/+bug/1860994

### PR DESCRIPTION
**Pull request by mymedia2**
This is my quick attempt to fix #29. I hope someone well experienced with GTK stuff would suggest more appropriate solution which takes theming into account, handles any encodings, and works with different character width. Compare the following:

 * iiiiiiiiiiiiiiiiiiiiiiiii
 * иииииииииииииииииииииииии
 * イイイイイイイイイイイイイイイイイイイイイイイイイ

All these strings consist of 25 characters however they have very different width in pixels. Another limitation of the patch is that it always truncates string with triple dots and does not treat word separators in a special way.

screenshot

### CODE REVIEW

**Comment by sunweaver** [comment]
@tari01 please take a look at this PR and review / improve. Thanks.

**Comment by sunweaver** [comment]
@mymedia2: thanks for working on ayatana-indicator-datetime.

**Comment by tari01** [comment]
@sunweaver  @mymedia2 

I will need to delay this for a while - we have a similar problem in the notifications indicator, and a working solution in the messages indicator. I would like to find a single common place to handle all this elipsizing.

**Comment by tari01** [comment]
@mymedia2 

We really appreciate your work on this, but I have implemented a solution that will work for all indicators. I hope you don't mind that I'm closing the pull request.

Details:
https://github.com/AyatanaIndicators/libayatana-common/pull/25
https://github.com/AyatanaIndicators/ayatana-indicator-datetime/pull/38

**Pull request closed without merging**
