### PR TITLE
Fix a couple of build failures on Ubuntu hirsute:

### PR DESCRIPTION
**Pull request by oSoMoN**
- src/engine-eds.cpp: use i_cal_component_free for ICalComponent
 - src/exporter.cpp: drop unnecessary G_OBJECT cast

### CODE REVIEW

**Review by tari01 — APPROVED** [review]
I confirm the build failure exists, and this fixes it.

**Comment by tari01** [comment]
@oSoMoN I was too quick to merge this without thinking: How does this affect Ubuntu 20.04/20.10?

**Comment by oSoMoN** [comment]
> @oSoMoN I was too quick to merge this without thinking: How does this affect Ubuntu 20.04/20.10?

That's a good question that I must admit I hadn't considered, but I just tested in chroots for 20.04 and 20.10, and the builds succeeded.

**Comment by tari01** [comment]
> That's a good question that I must admit I hadn't considered, but I just tested in chroots for 20.04 and 20.10, and the builds succeeded.

I have also tested it, no issues. Thanks for the contribution!

**Pull request merged**
