### PR TITLE
Do not export alarm properties on D-Bus

### PR DESCRIPTION
**Pull request by tari01**
fixes https://github.com/AyatanaIndicators/ayatana-indicator-datetime/issues/103

@JamiKettunen: Can I have your feedback on this, please?

### CODE REVIEW

**Comment by sunweaver** [comment]
@tari01: can you please improve the commit message "Do not export/test alarm properties on D-Bus" and explain why you think this to be the approach to go? In 6 months from now, that one-liner will let us frown and scratch our bald heads. Thanks!

**Comment by tari01** [comment]
> @tari01: can you please improve the commit message "Do not export/test alarm properties on D-Bus" and explain why you think this to be the approach to go? In 6 months from now, that one-liner will let us frown and scratch our bald heads. Thanks!

Amended. Review, but do not merge until @JamiKettunen confirms this actually solves the problem.

**Comment by JamiKettunen** [comment]
Hm I've not tested anything but wouldn't it be better to wait until UT 22.04 dev starts before merging this? Also does it **always** read the GSettings already every time when sounding alarm etc since after this it won't be possible to change them via D-Bus anymore like the [Clock app](https://gitlab.com/ubports/development/apps/clock-app) currently does when messing with the settings?

**Comment by tari01** [comment]
> Or I suppose rather is the internal state of the indicator for those props updated when changes to the GSettings happen?

Yes. The indicator tracks the GSettings internally and updates the variables accordingly. Nothing else is needed there.

This change (supposedly) only prevents the indicator from exporting those values to D-Bus to avoid the clash resulting from Lomiri already doing the same.

This should definitely be tested before merging.

**Comment by sunweaver** [comment]
@JamiKettunen please test this, if possible.

**Comment by sunweaver** [comment]
@JamiKettunen Is this PR still required / needed / valid? @tari01 Feedback?

I will close this PR now, please reopen if you want to pick up the thread again.

**Pull request closed without merging**
