### PR TITLE
ECal 2.0 fix and more...

### PR DESCRIPTION
**Pull request by tari01**
* Made GCC 10.1.0 friendly
* Fixed to work with ECal 2.0
* Added libaccounts-glib dependency
* Added mate-time-admin handler

@sunweaver 

Could you please also publish a release - Thanks

### CODE REVIEW

**Comment by ckristhoff** [comment]
Nice work, I'm getting next error in Manjaro with Mate

```
-- Checking for module 'url-dispatcher-1>=1'
--   Package 'url-dispatcher-1', required by 'virtual:world', not found
-- Checking for module 'dbustest-1>=14.04.0'
--   Package 'dbustest-1', required by 'virtual:world', not found
CMake Error at /usr/share/cmake-3.17/Modules/FindPkgConfig.cmake:497 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.17/Modules/FindPkgConfig.cmake:681 (_pkg_check_modules_internal)
  CMakeLists.txt:102 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/var/tmp/pamac-build-cristhiam/ayatana-indicator-datetime/build/CMakeFiles/CMakeOutput.log".

```

**Comment by tari01** [comment]
@ckristhoff 

You need to build it like this:

```
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBEXECDIR=lib -Denable_tests=OFF ..
make
```
You can look at the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ayatana-indicator-datetime).

To actually see it, you also need [mate-ayatana-indicator-applet](https://aur.archlinux.org/packages/mate-ayatana-indicator-applet/), and add "Indicator Applet Complete to the panel" (explained [here](https://tari.in/www/articles/ayatana/)).

**Comment by ckristhoff** [comment]
> @ckristhoff
> 
> You need to build it like this:
> 
> ```
> mkdir build
> cd build
> cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBEXECDIR=lib -Denable_tests=OFF ..
> make
> ```
> 
> You can look at the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ayatana-indicator-datetime).
> 
> To actually see it, you also need [mate-ayatana-indicator-applet](https://aur.archlinux.org/packages/mate-ayatana-indicator-applet/), and add **Indicator Applet Complete** to the panel (explained [here](https://tari.in/www/articles/ayatana/)).

Thank you so much.

**Comment by spikerguy** [comment]
Thanks @tari01 
This fixed the build issue for Manjaro ARM.
Here is the build log.
https://gitlab.manjaro.org/manjaro-arm/packages/community/lomiri-dev/ayatana-indicator-datetime-git/-/jobs/543

**Pull request merged**
