### PR TITLE
src/haptic.cpp: Fix data type sent to hfd-service

### PR DESCRIPTION
**Pull request by tari01**
fixes https://github.com/AyatanaIndicators/ayatana-indicator-datetime/issues/96

@sunweaver: This needs a blessing from @JamiKettunen.

### CODE REVIEW

**Comment by sunweaver** [comment]
@JamiKettunen Can you test and give feedback?

**Comment by JamiKettunen** [comment]
At least the previous errors no longer appear in `journalctl`, but there's still no vibration now; checking user `dbus-monitor` shows:
```
method call time=1668345268.339744 sender=:1.19 -> destination=com.lomiri.hfd serial=350 path=/com/lomiri/hfd; interface=com.lomiri.hfd.Vibrator; member=vibrate
   int32 1000
error time=1668345268.339891 sender=org.freedesktop.DBus -> destination=:1.19 error_name=org.freedesktop.DBus.Error.ServiceUnknown reply_serial=350
   string "The name com.lomiri.hfd was not provided by any .service files"
```
while `hfd-service-tools-vibrator` doesn't produce anything in `dbus-monitor`, so in fact it looks like we're missing the D-Bus interface for [`hfd-service`](https://gitlab.com/ubports/development/core/hfd-service)?

**Comment by JamiKettunen** [comment]
Actually I just thought about this more, could it be a problem that `/usr/libexec/hfd-service` runs as `root` while `/usr/libexec/ayatana-indicator-datetime/ayatana-indicator-datetime-service` runs as `phablet` user?

**Comment by tari01** [comment]
From the D-Bus error it seems to me that the hfd-service is either not running, or something (the policy?) is hiding it from the user. Hmm...

**Comment by JamiKettunen** [comment]
Can confirm that `dbus-send` vibrates my Volla Phone on UT 20.04 :)

**Comment by tari01** [comment]
I have changed the code to use the session bus. No errors on my side now. Could you re-test, please?

**Comment by JamiKettunen** [comment]
Working perfectly on my end now, LGTM!

**Pull request merged**
